/*
 * Copyright (c) 2022-2023 XiNGRZ
 * SPDX-License-Identifier: MIT
 *
 * HID LampArray report descriptor byte sequence.
 *
 * The descriptor declares the Microsoft HID LampArray usage page (0x59)
 * with six reports (Attributes / AttributesRequest / AttributesResponse /
 * MultiUpdate / RangeUpdate / Control). MultiUpdate Report #4 is variable-
 * length and is built at compile time using LISTIFY so the per-lamp
 * channel definitions are emitted once per lamp.
 *
 * The byte layout is ported from
 * https://github.com/taleroangel/zephyr-lamparray (MIT, Angel Talero).
 */

#ifndef HW75_LAMPARRAY_DESCRIPTOR_H_
#define HW75_LAMPARRAY_DESCRIPTOR_H_

#include <zephyr/sys/util.h>
#include <zephyr/usb/class/usb_hid.h>

#include "lamparray_reports.h"

/* ---- HID usage tags (Microsoft LampArray spec) ---- */

#define HW75_LAMPARRAY_USAGE_PAGE 0x59 /* Lighting and Illumination */
#define HW75_LAMPARRAY_USAGE 0x01       /* LampArray */

#define HW75_LAMPARRAY_USAGE_ATTR_REPORT 0x02
#define HW75_LAMPARRAY_USAGE_ATTR_REQUEST 0x20
#define HW75_LAMPARRAY_USAGE_ATTR_RESPONSE 0x22
#define HW75_LAMPARRAY_USAGE_MULTI_UPDATE 0x50
#define HW75_LAMPARRAY_USAGE_RANGE_UPDATE 0x60
#define HW75_LAMPARRAY_USAGE_CONTROL 0x70

#define HW75_LAMPARRAY_USAGE_LAMP_COUNT 0x03
#define HW75_LAMPARRAY_USAGE_BB_W 0x04
#define HW75_LAMPARRAY_USAGE_BB_H 0x05
#define HW75_LAMPARRAY_USAGE_BB_D 0x06
#define HW75_LAMPARRAY_USAGE_KIND 0x07
#define HW75_LAMPARRAY_USAGE_MIN_UPDT_INT 0x08
#define HW75_LAMPARRAY_USAGE_LAMP_ID 0x21
#define HW75_LAMPARRAY_USAGE_LAMP_ID_START 0x61
#define HW75_LAMPARRAY_USAGE_LAMP_ID_END 0x62
#define HW75_LAMPARRAY_USAGE_POS_X 0x23
#define HW75_LAMPARRAY_USAGE_POS_Y 0x24
#define HW75_LAMPARRAY_USAGE_POS_Z 0x25
#define HW75_LAMPARRAY_USAGE_LAMP_PURPOSES 0x26
#define HW75_LAMPARRAY_USAGE_UPDATE_LATENCY 0x27
#define HW75_LAMPARRAY_USAGE_RED_LEVELS 0x28
#define HW75_LAMPARRAY_USAGE_GREEN_LEVELS 0x29
#define HW75_LAMPARRAY_USAGE_BLUE_LEVELS 0x2A
#define HW75_LAMPARRAY_USAGE_INTENSITY_LEVELS 0x2B
#define HW75_LAMPARRAY_USAGE_IS_PROGRAMMABLE 0x2C
#define HW75_LAMPARRAY_USAGE_INPUT_BINDING 0x2D
#define HW75_LAMPARRAY_USAGE_UPDATE_FLAGS 0x55
#define HW75_LAMPARRAY_USAGE_RED_UPDT 0x51
#define HW75_LAMPARRAY_USAGE_GREEN_UPDT 0x52
#define HW75_LAMPARRAY_USAGE_BLUE_UPDT 0x53
#define HW75_LAMPARRAY_USAGE_INTENSITY_UPDT 0x54
#define HW75_LAMPARRAY_USAGE_AUTONOMOUS_MODE 0x71

#define HID_LAMPARRAY_COLLECTION_APP HID_COLLECTION(HID_COLLECTION_APPLICATION)
#define HID_LAMPARRAY_COLLECTION_LOGICAL HID_COLLECTION(HID_COLLECTION_LOGICAL)
#define HID_LAMPARRAY_END_COLLECTION HID_END_COLLECTION

/*
 * HID feature data byte encoding (HID spec 1.11 §6.2.2.7):
 *   bit 0: Data(0) / Constant(1)
 *   bit 1: Array(0) / Variable(1)
 *   bit 2: Absolute(0) / Relative(1)
 * For LampArray everything is read/write data that varies per element.
 */
#define HID_LAMPARRAY_FEATURE_DATA_VAR     0x02 /* Data | Variable | Absolute */
#define HID_LAMPARRAY_FEATURE_CONST_VAR    0x03 /* Constant | Variable | Absolute */

/*
 * 2-byte Report Count: HID spec requires a long item when the count
 * exceeds 255. The header byte is (tag << 4) | (type << 2) | size, where
 * size = 2 for a 2-byte data payload. Zephyr's HID_REPORT_COUNT macro
 * only emits 1-byte counts, so we hand-roll the 2-byte form here.
 */
#define HID_LAMPARRAY_REPORT_COUNT_2BYTE(c)                                                  \
	HID_ITEM(HID_ITEM_TAG_REPORT_COUNT, HID_ITEM_TYPE_GLOBAL, 2),                          \
		(uint8_t)((c) & 0xFF), (uint8_t)(((c) >> 8) & 0xFF)

/* Helper: one entry in the MultiUpdate lamp list. */
#define HW75_LAMPARRAY_LAMP_ENTRY(_, __)                                                  \
	HID_USAGE(HW75_LAMPARRAY_USAGE_RED_UPDT),                                            \
	HID_USAGE(HW75_LAMPARRAY_USAGE_GREEN_UPDT),                                          \
	HID_USAGE(HW75_LAMPARRAY_USAGE_BLUE_UPDT),                                           \
	HID_USAGE(HW75_LAMPARRAY_USAGE_INTENSITY_UPDT)

/* The descriptor. Parameterized by HW75_LAMPARRAY_LAMP_COUNT from the
 * per-board config header (injected via -include in the CMakeLists.txt).
 */
static const uint8_t hw75_lamparray_report_desc[] = {
	/* Usage Page (Lighting and Illumination) */
	HID_USAGE_PAGE(HW75_LAMPARRAY_USAGE_PAGE),
	HID_USAGE(HW75_LAMPARRAY_USAGE),
	HID_LAMPARRAY_COLLECTION_APP,

	/* Report 1: LampArrayAttributesReport */
	HID_REPORT_ID(LAMPARRAY_REPORT_ATTRIBUTES),
	HID_USAGE(HW75_LAMPARRAY_USAGE_ATTR_REPORT),
	HID_LAMPARRAY_COLLECTION_LOGICAL,

	/* LampCount (u16) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_COUNT),
	HID_LOGICAL_MIN16(0x00, 0x00),
	HID_LOGICAL_MAX16(0xFF, 0x00),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(2),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* BoundingBox W, H, D (3 × u32) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_BB_W),
	HID_USAGE(HW75_LAMPARRAY_USAGE_BB_H),
	HID_USAGE(HW75_LAMPARRAY_USAGE_BB_D),
	HID_LOGICAL_MIN32(0x00, 0x00, 0x00, 0x00),
	HID_LOGICAL_MAX32(0xFF, 0xFF, 0xFF, 0x7F),
	HID_REPORT_SIZE(32),
	HID_REPORT_COUNT(3),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* LampArrayKind (u32) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_KIND),
	HID_LOGICAL_MIN32(0x00, 0x00, 0x00, 0x00),
	HID_LOGICAL_MAX32(0xFF, 0xFF, 0xFF, 0x7F),
	HID_REPORT_SIZE(32),
	HID_REPORT_COUNT(1),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* MinUpdateIntervalInMicroseconds (u32) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_MIN_UPDT_INT),
	HID_LOGICAL_MIN32(0x00, 0x00, 0x00, 0x00),
	HID_LOGICAL_MAX32(0xFF, 0xFF, 0xFF, 0x7F),
	HID_REPORT_SIZE(32),
	HID_REPORT_COUNT(1),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	HID_LAMPARRAY_END_COLLECTION,

	/* Report 2: LampAttributesRequestReport */
	HID_REPORT_ID(LAMPARRAY_REPORT_ATTRIBUTES_REQUEST),
	HID_USAGE(HW75_LAMPARRAY_USAGE_ATTR_REQUEST),
	HID_LAMPARRAY_COLLECTION_LOGICAL,

	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_ID),
	HID_LOGICAL_MIN16(0x00, 0x00),
	HID_LOGICAL_MAX16(0xFF, 0x00),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(2),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	HID_LAMPARRAY_END_COLLECTION,

	/* Report 3: LampAttributesResponseReport */
	HID_REPORT_ID(LAMPARRAY_REPORT_ATTRIBUTES_RESPONSE),
	HID_USAGE(HW75_LAMPARRAY_USAGE_ATTR_RESPONSE),
	HID_LAMPARRAY_COLLECTION_LOGICAL,

	/* LampId (u16) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_ID),
	HID_LOGICAL_MIN16(0x00, 0x00),
	HID_LOGICAL_MAX16(0xFF, 0x00),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(2),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* Position X, Y, Z (3 × u32) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_POS_X),
	HID_USAGE(HW75_LAMPARRAY_USAGE_POS_Y),
	HID_USAGE(HW75_LAMPARRAY_USAGE_POS_Z),
	HID_LOGICAL_MIN32(0x00, 0x00, 0x00, 0x00),
	HID_LOGICAL_MAX32(0xFF, 0xFF, 0xFF, 0x7F),
	HID_REPORT_SIZE(32),
	HID_REPORT_COUNT(3),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* LampPurposes (u32) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_PURPOSES),
	HID_LOGICAL_MIN32(0x00, 0x00, 0x00, 0x00),
	HID_LOGICAL_MAX32(0xFF, 0xFF, 0xFF, 0x7F),
	HID_REPORT_SIZE(32),
	HID_REPORT_COUNT(1),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* UpdateLatencyInMicroseconds (u32) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_UPDATE_LATENCY),
	HID_LOGICAL_MIN32(0x00, 0x00, 0x00, 0x00),
	HID_LOGICAL_MAX32(0xFF, 0xFF, 0xFF, 0x7F),
	HID_REPORT_SIZE(32),
	HID_REPORT_COUNT(1),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* RedLevelCount, GreenLevelCount, BlueLevelCount, IntensityLevelCount,
	 * IsProgrammable, InputBinding (6 × u8) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_RED_LEVELS),
	HID_USAGE(HW75_LAMPARRAY_USAGE_GREEN_LEVELS),
	HID_USAGE(HW75_LAMPARRAY_USAGE_BLUE_LEVELS),
	HID_USAGE(HW75_LAMPARRAY_USAGE_INTENSITY_LEVELS),
	HID_USAGE(HW75_LAMPARRAY_USAGE_IS_PROGRAMMABLE),
	HID_USAGE(HW75_LAMPARRAY_USAGE_INPUT_BINDING),
	HID_LOGICAL_MIN8(0x00),
	HID_LOGICAL_MAX8(0xFF),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(6),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	HID_LAMPARRAY_END_COLLECTION,

	/* Report 4: LampMultiUpdateReport */
	HID_REPORT_ID(LAMPARRAY_REPORT_MULTI_UPDATE),
	HID_USAGE(HW75_LAMPARRAY_USAGE_MULTI_UPDATE),
	HID_LAMPARRAY_COLLECTION_LOGICAL,

	/* LampCount (u8) + LampUpdateFlags (u8) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_COUNT),
	HID_USAGE(HW75_LAMPARRAY_USAGE_UPDATE_FLAGS),
	HID_LOGICAL_MIN8(0x00),
	HID_LOGICAL_MAX8(HW75_LAMPARRAY_LAMP_COUNT),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(2),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* LampId list (HW75_LAMPARRAY_LAMP_COUNT × u16) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_ID),
	HID_LOGICAL_MIN16(0x00, 0x00),
	HID_LOGICAL_MAX16(0xFF, 0x00),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(HW75_LAMPARRAY_LAMP_COUNT * 2),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* Per-lamp update channels (HW75_LAMPARRAY_LAMP_COUNT × {R,G,B,Intensity} u8 each).
	 * HW75_LAMPARRAY_LAMP_COUNT * 4 can exceed 255 on the keyboard (101 lamps,
	 * 404 channels) so the count is emitted as a 2-byte long item.
	 */
	LISTIFY(HW75_LAMPARRAY_LAMP_COUNT, HW75_LAMPARRAY_LAMP_ENTRY, (,)),
	HID_LOGICAL_MIN8(0x00),
	HID_LOGICAL_MAX8(0xFF),
	HID_REPORT_SIZE(8),
	HID_LAMPARRAY_REPORT_COUNT_2BYTE(HW75_LAMPARRAY_LAMP_COUNT * 4),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	HID_LAMPARRAY_END_COLLECTION,

	/* Report 5: LampRangeUpdateReport */
	HID_REPORT_ID(LAMPARRAY_REPORT_RANGE_UPDATE),
	HID_USAGE(HW75_LAMPARRAY_USAGE_RANGE_UPDATE),
	HID_LAMPARRAY_COLLECTION_LOGICAL,

	/* LampUpdateFlags (u8) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_UPDATE_FLAGS),
	HID_LOGICAL_MIN8(0x00),
	HID_LOGICAL_MAX8(0x08),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(1),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* LampIdStart, LampIdEnd (2 × u16) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_ID_START),
	HID_USAGE(HW75_LAMPARRAY_USAGE_LAMP_ID_END),
	HID_LOGICAL_MIN16(0x00, 0x00),
	HID_LOGICAL_MAX16(0xFF, 0x00),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(4),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	/* RedUpdateChannel, GreenUpdateChannel, BlueUpdateChannel,
	 * IntensityUpdateChannel (4 × u8) */
	HID_USAGE(HW75_LAMPARRAY_USAGE_RED_UPDT),
	HID_USAGE(HW75_LAMPARRAY_USAGE_GREEN_UPDT),
	HID_USAGE(HW75_LAMPARRAY_USAGE_BLUE_UPDT),
	HID_USAGE(HW75_LAMPARRAY_USAGE_INTENSITY_UPDT),
	HID_LOGICAL_MIN8(0x00),
	HID_LOGICAL_MAX8(0xFF),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(4),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	HID_LAMPARRAY_END_COLLECTION,

	/* Report 6: LampArrayControlReport */
	HID_REPORT_ID(LAMPARRAY_REPORT_CONTROL),
	HID_USAGE(HW75_LAMPARRAY_USAGE_CONTROL),
	HID_LAMPARRAY_COLLECTION_LOGICAL,

	HID_USAGE(HW75_LAMPARRAY_USAGE_AUTONOMOUS_MODE),
	HID_LOGICAL_MIN8(0x00),
	HID_LOGICAL_MAX8(0x01),
	HID_REPORT_SIZE(8),
	HID_REPORT_COUNT(1),
	HID_FEATURE(HID_LAMPARRAY_FEATURE_DATA_VAR),

	HID_LAMPARRAY_END_COLLECTION,

	HID_LAMPARRAY_END_COLLECTION,
};

#endif /* HW75_LAMPARRAY_DESCRIPTOR_H_ */